version: "3.7"
services:
  notebook:
    build: .
    container_name: "${PROJECT_NAME}_notebook"
    command: jupyter notebook
    ports:
      - 8888:8888
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./data:/home/jovyan/data
      - ./models:/home/jovyan/models
