version: "3.3"
services:
  notebook:
    build: .
    image: magenta-notebook
    container_name: "${PROJECT_NAME}_notebook"
    command: jupyter notebook
    ports:
      - 8888:8888
    volumes:
      - ./:/home/jovyan
